# CodingCoffee  C/C++ GitPod Examples more courses : http://www.codingcoffee.org
tasks:
  - init: echo 'this is Linux System programming gitpod example' # runs during prebuild
    command: echo ' CodingCoffee System Programming Tutorial '

# CodingCoffee  C/C++ GitPod Examples more courses : http://www.codingcoffee.org
ports:
  - port: 3000
    onOpen: open-preview
